[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qafm"
version = "0.1.0"
description = "Quantitative AFM force models and analysis utilities"
keywords = ["afm", "atomic force microscopy", "quantitative", "force measurement"]
readme = "README.md"
authors = [
    { name = "Jannik Evers" }, 
    { name = "Philipp Rahe" }
]
license = "BSD-3-Clause"
license-files = ["LICENSE"]
# Note: collections, math, inspect, dataclasses are in core python, 
# Do not list here
dependencies = [
    "numpy>=1.21",
    "scipy>=1.8",
]
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/MolQS/qafm/"
Documentation = "https://qafm.readthedocs.io"
Repository = "https://github.com/MolQS/qafm/"

[project.optional-dependencies]
plot = [
    "matplotlib",
]
io = [
    "h5py",
]
dev = [
    "pytest",
    "matplotlib",
    "h5py",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
